### PR TITLE
properly dispose

### PR DESCRIPTION
**Pull request by marknadig**
Aiming for exemplary code examples: dispose HubConnection in examples

@Rick-Anderson  edit 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-net-client?branch=pr-en-us-237)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@bradygaster   can you assign someone to review this?

**Comment by anurse** [comment]
Unfortunately this also makes all the references to the sample incorrect, they highlight line numbers. For example:

image

The `aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-net-client.md` file will need to be updated to have correct highlight references before we can take this change.

Added @BrennanConroy and @halter73 for review (heads-up, this is ASP.NET SignalR content, not ASP.NET Core).

**Comment by Rick-Anderson** [comment]
@anurse  if the code changes are correct, I can have @wadepickett fix the highlighting.

I'll give @marknadig  first shot at fixing highlighting.

**Comment by Rick-Anderson** [comment]
@anurse  thanks. If @marknadig  doesn't update, I'll have @wadepickett  before I merge.

**Comment by wadepickett** [comment]
@Rick-Anderson, looks good.  Ready to merge.

**Pull request merged**
