### PR TITLE
LocalizationFix: Fixes #1578493

### PR DESCRIPTION
**Pull request by damabe**
[Internal Bug](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1578493)

This PR fixes user story 1578493.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@damabe  rich diff doesn't show any difference. What's  #1578493 ?

**Comment by Rick-Anderson** [comment]
If it's an internal bug (not GitHub), don't  use gitHub notation (`#bug number`)
Use `[Internal bug](URI to bug)`

**Comment by damabe** [comment]
@Rick-Anderson It's the user story (https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1578493). I had to fix some bold/italic formatting in the tutorial conclusion section.

**Comment by tfosmark** [comment]
#sign-off

**Comment by tfosmark** [comment]
@mcleblanc

**Pull request merged**
