### PR TITLE
JPG image conversions to PNG

### PR DESCRIPTION
**Pull request by pgoldman5699**
#hold-off    

@v-makoud 

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1557067/

image conversions from jpg to png

### CODE REVIEW

**Comment by tfosmark** [comment]
@pgoldman5699 One of the images in **aspnet/web-pages/overview/ui-layouts-and-themes/3-creating-a-consistent-look.md** is not rendering correctly. It appears that the new .png file needs to be in the **/_static** subdirectory.

**Comment by pgoldman5699** [comment]
@tfosmark 

Good catch. Should be okay now.

**Comment by tfosmark** [comment]
#sign-off

**Comment by tfosmark** [comment]
@Rick-Anderson Who do we contact to merge?

**Pull request merged**
