### PR TITLE
C90831: Link is in wrong format

### PR DESCRIPTION
**Pull request by v-makoud**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.

### CODE REVIEW

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-maudel** [comment]
Hi @Rick-Anderson , could you please check this change and merge if agree?
Regards.

**Comment by Rick-Anderson** [comment]
@v-makoud  thanks

**Comment by v-maudel** [comment]
Thanks @Rick-Anderson

**Pull request merged**
