### PR TITLE
Correct the information about Required attribute

### PR DESCRIPTION
**Pull request by cnolewajka**
Corrects the information about the Required attribute and its replacement with StringLength attribute and MinimumLength property.
They are not synonymous.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@cnolewajka  see https://github.com/aspnet/AspNetCore.Docs/pull/13988 for my proposed fix.

**Comment by Rick-Anderson** [comment]
@cnolewajka can you apply the same write up we used in  aspnet/AspNetCore.Docs#13988

**Comment by cnolewajka** [comment]
@Rick-Anderson you mean on my fork? and if not, then apply where?

**Comment by Rick-Anderson** [comment]
Sure, that works. Or you can edit the file in the browser.

**Comment by cnolewajka** [comment]
Created the PR:  https://github.com/aspnet/AspNetDocs/pull/213

**Pull request closed without merging**
