### PR TITLE
Changed Product to ProductServiceModel

### PR DESCRIPTION
**Pull request by RosenDev**
ProductService should return ProductServiceModel instead of pure Entity Model.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  I think @RosenDev  is correct.

**Comment by tdykstra** [comment]
@Rick-Anderson I don't see ProductServiceModel anywhere else in these docs.

**Comment by RosenDev** [comment]
Yes I did it only in the page, I saw is wrong.

**Comment by Rick-Anderson** [comment]
How is it wrong?

**Comment by RosenDev** [comment]
I wrote it in the pull request description.
I mean the example is wrong.
Service should return ProductServiceModel instead of Product.

**Pull request closed without merging**
