### PR TITLE
The example of the real business application added

### PR DESCRIPTION
**Pull request by Anna-Angelova**
In the Summary section, the example of the nopCommerce open-source shopping cart added. Originally, it was built on Web Forms and over the years it moved to MVC and now to ASP.NET Core.
It will help to understand how the functionality described above works in a real business application.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@danroth27 I don't think the shopping cart sample we provide in this tutorial would pass a product unit review.  It looks like https://www.nopcommerce.com/ is established. Given we don't link to products where we haven't done a review, and we don't have time - Can you make an exception for this? This is not Core.

**Comment by AndreiMaz** [comment]
@Rick-Anderson @danroth27 Not sure what kind of a product unit review you mean. But I know that Scott Hanselman did some review on his website about nopCommerce. Please check it out at  https://www.hanselman.com/blog/ExploringNopCommerceOpenSourceEcommerceShoppingCartPlatformInNETCore.aspx

**Comment by AndreiMaz** [comment]
Thanks a lot, guys!

**Comment by Rick-Anderson** [comment]
Thank you. This will help our customers.
They need to look at your product and ignore our sample cart.

**Pull request merged**
